# Generated by Django 5.1.15 on 2026-08-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('login_failed', 'Login failed'), ('logout', 'Logout'), ('signup', 'Signup (owner bootstrap)'), ('session_expired', 'Session expired (new device login)'), ('other', 'Other')], max_length=20),
        ),
    ]
