# Generated by Django 5.1.15 on 2026-08-04 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='served_by',
            field=models.ForeignKey(blank=True, help_text='The staff member who actually took/served this order — may differ from created_by on a shared terminal login. Defaults to created_by if not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_served', to=settings.AUTH_USER_MODEL),
        ),
    ]
